name: BlogHub CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "apply or destroy"
        required: true
        default: "apply"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACTION: ${{ github.event.inputs.action || 'apply' }}
      AWS_REGION: ap-south-1
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/bloghub:${{ github.sha }}
      DOCKER_IMAGE_LATEST: ${{ secrets.DOCKERHUB_USERNAME }}/bloghub:latest
      DATABASE_USERNAME: bloghub_admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Login to Docker Hub
        if: env.ACTION == 'apply'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: env.ACTION == 'apply'
        working-directory: app
        run: |
          docker build -t "$DOCKER_IMAGE" -t "$DOCKER_IMAGE_LATEST" .
          docker push "$DOCKER_IMAGE"
          docker push "$DOCKER_IMAGE_LATEST"

      - name: Terraform Apply
        if: env.ACTION == 'apply'
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="db_password=${{ secrets.DB_PASSWORD }}"

      - name: Get Terraform Outputs
        if: env.ACTION == 'apply'
        working-directory: terraform
        run: |
          echo "DATABASE_URL=$(terraform output -raw database_url)" >> "$GITHUB_ENV"
          echo "APP_SERVER_IP=$(terraform output -raw app_server_ip)" >> "$GITHUB_ENV"

      - name: Deploy App on EC2
        if: env.ACTION == 'apply'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.APP_SERVER_IP }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull $DOCKER_IMAGE_LATEST

            docker stop bloghub || true
            docker rm bloghub || true

            docker run -d \
              -p 8080:8082 \
              -e DB_URL=${{ env.DATABASE_URL }} \
              -e DB_USER=${{ env.DATABASE_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              --name bloghub \
              $DOCKER_IMAGE_LATEST

      - name: Terraform Destroy
        if: env.ACTION == 'destroy'
        working-directory: terraform
        run: |
          terraform init
          terraform destroy -auto-approve \
            -var="db_password=${{ secrets.DB_PASSWORD }}"
